name: jupyter
on:
  push:
    paths:
      - "jupyter/Dockerfile"
  workflow_dispatch:
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to docker hub
        run: echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin
      - name: Run Buildx
        working-directory: ./jupyter
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --tag ${{secrets.docker_username}}/jupyter:latest \
            .
